"""
Phase 4: Complete End-to-End Retrieval Example

This script demonstrates the full workflow:
1. Load an image
2. Extract a patch
3. Encode it with DA-CLIP
4. Query FAISS index
5. Load retrieved patches
6. Visualize results

Usage:
    python example_retrieval.py
"""

import sys
from pathlib import Path
import json
import numpy as np

# Add src to path
SRC_DIR = Path(__file__).parent / "src"
sys.path.insert(0, str(SRC_DIR))

from modules.da_clip_encoder import DACLIPEncoder
from modules.patch_extraction import PatchExtractor
from retrieval import FAISSIndexLoader, PatchRetriever, PatchLoader
from visualization import RetrievalVisualizer


def main():
    print("\n" + "="*70)
    print("DA-CLIP IMAGE RESTORATION - PHASE 4 RETRIEVAL EXAMPLE")
    print("="*70)
    
    # Configuration
    config = {
        'patch_size': 64,
        'stride': 32,
        'k': 5,  # Number of patches to retrieve
        'normalize': True,
        'device': None,  # Auto-detect
    }
    
    base_dir = Path(__file__).parent
    images_dir = base_dir / "images"
    indexes_dir = base_dir / "indexes"
    
    print(f"\n Directories:")
    print(f"   Base: {base_dir}")
    print(f"   Images: {images_dir}")
    print(f"   Indexes: {indexes_dir}")
    
    # Step 1: Initialize DA-CLIP encoder
    print("\n" + "-"*70)
    print("STEP 1: Initialize DA-CLIP Encoder")
    print("-"*70)
    
    try:
        encoder = DACLIPEncoder(
            model_name="ViT-B-32",
            pretrained="laion2b_s34b_b79k",
            normalize=config['normalize'],
            device=config['device'],
            debug=True
        )
    except Exception as e:
        print(f" Error initializing encoder: {e}")
        print("   Make sure open-clip-torch is installed:")
        print("   pip install open-clip-torch")
        return False
    
    # Step 2: Load and extract patch from image
    print("\n" + "-"*70)
    print("STEP 2: Extract Patch from Image")
    print("-"*70)
    
    try:
        image_files = list(images_dir.glob("*.png")) + list(images_dir.glob("*.jpg"))
        if not image_files:
            print(f" No images found in {images_dir}")
            return False
        
        image_path = image_files[0]
        print(f"Loading: {image_path.name}")
        
        extractor = PatchExtractor(
            patch_size=config['patch_size'],
            stride=config['stride']
        )
        patches, coords = extractor.extract(image_path, return_coords=True, debug=True)
        
        # Select a patch from the middle
        patch_idx = len(patches) // 2
        query_patch = patches[patch_idx]
        query_coords = coords[patch_idx]
        
        print(f"\n Selected patch {patch_idx}:")
        print(f"   Location: {query_coords}")
        print(f"   Shape: {query_patch.shape}")
        print(f"   Dtype: {query_patch.dtype}")
        print(f"   Range: [{query_patch.min()}, {query_patch.max()}]")
    
    except Exception as e:
        print(f" Error extracting patches: {e}")
        return False
    
    # Step 3: Encode patch with DA-CLIP
    print("\n" + "-"*70)
    print("STEP 3: Encode Patch with DA-CLIP")
    print("-"*70)
    
    try:
        query_embedding = encoder.encode_patch(query_patch, debug=True)
        
        print(f"\n Encoding successful:")
        print(f"   Shape: {query_embedding.shape}")
        print(f"   Dtype: {query_embedding.dtype}")
        print(f"   L2 Norm: {query_embedding.norm(p=2, dim=-1).item():.6f}")
        
        # Convert to numpy for FAISS
        query_embedding_np = query_embedding.numpy()
    
    except Exception as e:
        print(f" Error encoding patch: {e}")
        return False
    
    # Step 4: Load FAISS index and patch map
    print("\n" + "-"*70)
    print("STEP 4: Load FAISS Index and Patch Map")
    print("-"*70)
    
    try:
        loader = FAISSIndexLoader(debug=True)
        
        index_path = indexes_dir / "clean_patches.index"
        patch_map_path = indexes_dir / "patch_map.json"
        
        if not index_path.exists() or not patch_map_path.exists():
            print(f"\n  Index files not found:")
            print(f"   Index: {index_path} - {index_path.exists()}")
            print(f"   Map: {patch_map_path} - {patch_map_path.exists()}")
            print("\n   Skipping retrieval (index not available)")
            print("   These files should be generated by Phase 3 indexing")
            return True  # Not a failure, just skip retrieval
        
        index = loader.load_index(index_path)
        patch_map = loader.load_patch_map(patch_map_path)
        
        print(f"\n Index loaded successfully")
    
    except Exception as e:
        print(f" Error loading index: {e}")
        print("   Make sure faiss is installed:")
        print("   pip install faiss-cpu")
        return False
    
    # Step 5: Retrieve top-k patches
    print("\n" + "-"*70)
    print("STEP 5: Retrieve Top-k Similar Patches")
    print("-"*70)
    
    try:
        retriever = PatchRetriever(
            index, patch_map,
            normalize_query=config['normalize'],
            debug=True
        )
        
        indices, distances, metadata = retriever.search(
            query_embedding_np,
            k=config['k'],
            return_metadata=True,
            debug=True
        )
        
        print(f"\n Retrieval successful:")
        print(f"   Retrieved {len(metadata)} patches")
        print(f"\n   Top-k Results:")
        print(f"   {'Rank':<6} {'Image':<25} {'Coords':<12} {'Distance':<10}")
        print(f"   {'-'*6} {'-'*25} {'-'*12} {'-'*10}")
        for i, meta in enumerate(metadata):
            coords_str = f"({meta['x']}, {meta['y']})"
            print(f"   {i+1:<6} {meta['image']:<25} {coords_str:<12} {meta['distance']:<10.6f}")
    
    except Exception as e:
        print(f" Error during retrieval: {e}")
        return False
    
    # Step 6: Load retrieved patches
    print("\n" + "-"*70)
    print("STEP 6: Load Retrieved Patches from Images")
    print("-"*70)
    
    try:
        patch_loader = PatchLoader(dataset_root=images_dir, debug=True)
        
        retrieved_patches = patch_loader.load_patches_from_metadata(
            metadata,
            patch_size=config['patch_size'],
            debug=True
        )
        
        print(f"\n Loaded {len(retrieved_patches)} patches:")
        for i, patch in enumerate(retrieved_patches):
            print(f"   Patch {i+1}: shape={patch.shape}, dtype={patch.dtype}, range=[{patch.min()}, {patch.max()}]")
    
    except Exception as e:
        print(f"  Error loading patches: {e}")
        retrieved_patches = None
    
    # Step 7: Visualize results
    print("\n" + "-"*70)
    print("STEP 7: Visualize Retrieval Results")
    print("-"*70)
    
    try:
        visualizer = RetrievalVisualizer(figsize=(14, 6), debug=True)
        
        if retrieved_patches:
            fig = visualizer.visualize_retrieval(
                query_patch,
                retrieved_patches,
                distances=distances[0],
                save_path=base_dir / "retrieval_result.png",
                show=True
            )
            print(f"\n Visualization saved to: {base_dir / 'retrieval_result.png'}")
        else:
            print(f"  Skipping visualization (no patches loaded)")
    
    except Exception as e:
        print(f"  Error visualizing results: {e}")
        print("   Make sure matplotlib is installed:")
        print("   pip install matplotlib")
    
    # Summary
    print("\n" + "="*70)
    print("PHASE 4 RETRIEVAL COMPLETE")
    print("="*70)
    print(f"\n Workflow Summary:")
    print(f"   1. Loaded DA-CLIP encoder")
    print(f"   2. Extracted patch from: {image_path.name}")
    print(f"   3. Encoded patch to embedding (dim={query_embedding_np.shape[-1]})")
    print(f"   4. Loaded FAISS index ({index.ntotal:,} patches)")
    print(f"   5. Retrieved top-{config['k']} similar patches")
    if retrieved_patches:
        print(f"   6. Loaded {len(retrieved_patches)} patch images")
        print(f"   7. Visualized results")
    else:
        print(f"   6. Skipped loading (image dataset not available)")
    
    print(f"\n Next Steps:")
    print(f"   - Review retrieval results for quality")
    print(f"   - If satisfied, proceed to Phase 5: Context Fusion")
    print(f"   - If dissatisfied, debug embeddings or FAISS index")
    
    return True


if __name__ == "__main__":
    try:
        success = main()
        sys.exit(0 if success else 1)
    except KeyboardInterrupt:
        print("\n\n  Interrupted by user")
        sys.exit(1)
    except Exception as e:
        print(f"\n Unexpected error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
